### ISSUE TITLE
From Edit to translatable state: also possible for information centre and events?

### ISSUE THREAD

**Issue by AnneliesVerroken** [micado-eu/pa_application#118]
I have been able to put a guided process in a translatable state, translate on weblate and get published after. I wanted to the same for  the other types of info, but:
• an information sheet: it returns to editing state and is editable indeed, so it does not go into the translatable state.
•  an event, the 3 statuses appear white (none is highlighted), but when trying to edit, there is a warning on top of the page.

Is all this because this is just not ready yet or am I doing something wrong?

**Comment by ivchicano** [comment]
About the information sheet issue it was indeed a bug, the content did go into the translatable state but it wasn't shown correctly, it is now fixed.
About the event issue, the 3 buttons appearing white means that the content has been translated into all the languages (unless there is a bug). We will review if there should be a way to see this more clearly.
Note however that there is currently a bug preventing sending to translation the content.

**Comment by ivchicano** [comment]
The events, information centre and glossary (common words) still show all content, not only the published one, this is still work in progress, so you can still see the content even if it's not translated/published in these pages.
If some things are missing from the layout it might be because you are not logged in.

**Comment by GiuseppeCSI** [comment]
Right now processes are the only one for which you can only see published  stuff. As Ivan said, we're still in the process of implementing it for all the content. The information portal was missing because someone was probably testing the feature selection on the PA app and disabled it. I re-enabled it, so you should be able to see it now

**Comment by AnneliesVerroken** [comment]
It is back indeed, thank you! 
Great, if I can work for the next hour in events and information centre, that is enough for me ;)
