### ISSUE TITLE
General: Re-check user type icons

### ISSUE THREAD

**Issue by balcse** [micado-eu/pa_application#125]
User-Type-Icons (e.g. migrants, refugees, etc). not intuitively understandable and confusing ("lots of little figurines") >> should be better differntiated visually AND should be explained visibly (for example by displaying the label when hovering over it)

**Comment by Leo-Moertenhuber** [comment]
I believe the tooltip will be a big help

for the visual, we need to keep 2 things in mind 
- with the icon size at 24x24px in the PA app, we don´t have a lot of room to adapt/ detail the icons since too many details will be counterproductive at that size 
- each of the 3 terms migrant, asylum seeker and refugee include many different aspects that are difficult to explain in such a small icon / come with issues trying to create one clear visual symbol for each 

with regards to that, I can offer 3 different solutions where I would need some feedback 
1) we try  to use just imagery 

     ![aslyum refugee_L-46](https://user-images.githubusercontent.com/61981568/105482079-321db180-5ca8-11eb-9983-1bb35357fa25.png) (asylum seeker) 

     ![aslyum refugee_L-47](https://user-images.githubusercontent.com/61981568/105482081-32b64800-5ca8-11eb-89d1-6ffc0b0dcd8f.png) (migrant)

     ![aslyum refugee_Artboard copy 69](https://user-images.githubusercontent.com/61981568/105482082-32b64800-5ca8-11eb-8320-6a4da99feb3a.png) (refugee)

here some issue would be for example that not every asylum seeker is specifically looking for a house or that not every refugee is running away from an explosion (I am not sure how such imagery would come across to the user groups themselves) 

2) we combine imagery with the first letter of each group 

     ![Micado APP Icons 1st 100_Artboard copy 95](https://user-images.githubusercontent.com/61981568/105482805-31d1e600-5ca9-11eb-98ae-946671acfd0c.png)

     ![Micado APP Icons 1st 100__](https://user-images.githubusercontent.com/61981568/105482848-43b38900-5ca9-11eb-9b09-5b927e3ae13e.png)

     ![Micado APP Icons 1st 100_Artboard copy 67 1](https://user-images.githubusercontent.com/61981568/105482984-765d8180-5ca9-11eb-9c4b-f1ca13788c15.png)

3) we completely remove imagery and just work with the first letters 

     ![Micado APP Icons 1st 100_Artboard copy 97](https://user-images.githubusercontent.com/61981568/105483078-92f9b980-5ca9-11eb-9878-f2ae38b94c66.png)

     ![Micado APP Icons 1st 100__ copy 5](https://user-images.githubusercontent.com/61981568/105483116-a0af3f00-5ca9-11eb-91ce-59266bb783b7.png)

     ![Micado APP Icons 1st 100_Artboard copy 96](https://user-images.githubusercontent.com/61981568/105483134-aa38a700-5ca9-11eb-850a-f5cade4552c2.png)

I feel that including the first letters in combination with a tooltip is the best way to go - so I would favor option 2 or 3

**Comment by ivchicano** [comment]
I like option 3 because they are also neutral, as if I recall correctly someone said that the previous icons could be considered offensive.
Even still I have the following question: Can the PA change these icons by themselves, or evenremove these user types and add other ones? Are these ones considered default?

**Comment by GiuseppeCSI** [comment]
As far as I am aware these three should be the default and the PA can then add their own(of course it would be on them making the new icons). Also, the PA can change all the icons from the forms in the frontend.
About the style of the icons I would also go for option number three. I have changed the icon to be those represented in option number 3 so people can see the effect

**Comment by gioppoluca** [comment]
My personal consideration.
Using letters is something that work ONLY in english since in italian, for example, the words stars with other letters.
I believe that we are really investing too much effort on this topic, but lucily each partner can change the icon as he please in his own locatio so I'd call this close
