### ISSUE TITLE
Guided process: in Dutch: unable to enter title of process and title of steps

### ISSUE THREAD

**Issue by AnneliesVerroken** [micado-eu/pa_application#98]
![Titel in het NDL ingeven lukt niet](https://user-images.githubusercontent.com/75615204/101632897-cc8ea200-3a26-11eb-8c5e-635b8c7e1361.PNG)

Guided process: in Dutch: unable to enter title of process , same for the titles of the different steps

**Comment by GiuseppeCSI** [comment]
It is indeed a bug, but for a different reason. We decided on the following approach: the language setting in the app will decide in which language you can write. After release, you will have the app set in dutch and will be able to write only in dutch. The other languages will be managed via the translation platform, so that we reduce the chances of translation errors. The app that's online right now is set to english, so you shouldn't be able to write in dutch.
Probably we didn't share or didn't make clear this thing, but right now you should test it by using the english fields.
I hope now it's more clear, I'll proceed with fixing the bug

**Comment by GiuseppeCSI** [comment]
Fixed with commit a52faec5c11b5e60c2d7cadbe8973dec9740bc6b
